version: "3"

services:
  influxdb:
    image: influxdb:latest
    hostname: influxdb
    container_name: influxdb
    restart: always
    ports:
    - "8086:8086"
    dns:
      - 10.200.0.254
    networks:
     private_network:
      ipv4_address: 10.200.0.131
    volumes:
      - /srv/docker/tig/influxdb/data:/var/lib/influxdb2
      - /srv/docker/tig/influxdb/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${mode}
      - DOCKER_INFLUXDB_INIT_USERNAME=${username}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${password}
      - DOCKER_INFLUXDB_INIT_ORG=${org}
      - DOCKER_INFLUXDB_INIT_BUCKET=${bucket}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${token}

  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    container_name: grafana
    restart: always
    ports:
    - "3000:3000"
    environment:
    - TZ=Europe/Madrid
    dns:
    - 10.200.0.254
    networks:
     private_network:
      ipv4_address: 10.200.0.132
    volumes:
    - /srv/docker/tig/grafana/provisioning:/etc/grafana/provisioning
    - /srv/docker/tig/grafana/data:/var/lib/grafana
    depends_on:
      - influxdb
