version: "3"

services:
  influxdb:
    image: influxdb:latest
    hostname: influxdb
    container_name: influxdb
    restart: always
#    ports:
#    - "8086:8086"
    dns:
      - ${VAR}
    networks:
     private_network:
      ipv4_address: ${VAR}
    volumes:
      - /srv/docker/tig/influxdb/data:/var/lib/influxdb2
      - /srv/docker/tig/influxdb/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${VAR}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${VAR}
      - DOCKER_INFLUXDB_INIT_ORG=${VAR}
      - DOCKER_INFLUXDB_INIT_BUCKET=${VAR}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${VAR}

  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - TZ=Europe/Madrid
    dns:
      - ${VAR}
    networks:
     private_network:
      ipv4_address: ${VAR}
    volumes:
    - /srv/docker/tig/grafana/provisioning:/etc/grafana/provisioning
    - /srv/docker/tig/grafana/data:/var/lib/grafana
    depends_on:
      - influxdb

networks:version: "3"

services:
  influxdb:
    image: influxdb:latest
    hostname: influxdb
    container_name: influxdb
    restart: always
    ports:
    - "8086:8086"
    dns:
      - 10.200.0.254
    networks:
     private_network:
      ipv4_address: 10.200.0.131
    volumes:
      - /srv/docker/tig/influxdb/data:/var/lib/influxdb2
      - /srv/docker/tig/influxdb/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${mode}
      - DOCKER_INFLUXDB_INIT_USERNAME=${username}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${password}
      - DOCKER_INFLUXDB_INIT_ORG=${org}
      - DOCKER_INFLUXDB_INIT_BUCKET=${bucket}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${token}

  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    container_name: grafana
    restart: always
    ports:
    - "3000:3000"
    environment:
    - TZ=Europe/Madrid
    dns:
    - 10.200.0.254
    networks:
     private_network:
      ipv4_address: 10.200.0.132
    volumes:
    - /srv/docker/tig/grafana/provisioning:/etc/grafana/provisioning
    - /srv/docker/tig/grafana/data:/var/lib/grafana
    depends_on:
      - influxdb

  geoipupdate:
    image: maxmindinc/geoipupdate
    hostname: geoipupdate
    container_name: geoipupdate
    environment:
      - GEOIPUPDATE_ACCOUNT_ID=${account}
      - GEOIPUPDATE_LICENSE_KEY=${license_key}
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-City
      - GEOIPUPDATE_FREQUENCY=24
    volumes:
      - /srv/docker/tig/geoip:/usr/share/GeoIP
    dns:
      - 10.200.0.254
    networks:
     private_network:
      ipv4_address: 10.200.0.135

networks:
  private_network:
    name: docker_private_network
    external: true
  private_network:
    name: ${VAR}
    external: true
